author = "Joe Curtin"
email = "42@jbcurtin.io"
url = "https://jbcurtin.io/"
locale = "en_US"
title = "Joe Curtin's Notebook(s)"
description = "jbcurtin.io has scripts for managing massive amounts of data to help you or your organization focus more on science"
keywords = "k8,kubenetes,aws,gcp,sklearn,mlops,modelops,numpy,devops,etl,astronomy,science,dask"
robots_title = "Joe Curtin's Robots.txt"
atom_title = "Joe Curtin's Atom Feed"
rss_title = "Joe Curtin's RSS Feed"
sitemap_title = "Joe Curtin's Sitemap"
recently_published_title = "Joe Curtin's Recently Published Notebooks and Articles"
index_title = "Joe Curtin's Index"
