author = "Joe curtin"
email = "42@jbcurtin.io"
url = "https://jbcurtin.io"
locale = "en_US"
title = "jbcurtin.io Index"
description = "jbcurtin.io has scripts for managing massive amounts of data to help you or your organization focus more on science"
keywords = "numpy,devops,etl,astronomy,science,dask"
