author = "Joe curtin"
email = "42@jbcurtin.io"
url = "https://data-scripts.com"
locale = "en_US"
title = "data-scripts Index"
description = "data-scripts has scripts for managing massive amounts of data to help you or your organization focus more on science"
keywords = "numpy,devops,etl,astronomy,science,dask"
